services:
  - type: web
    name: topstep-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TOPSTEP_API_KEY
        value: 4s/YUAhW2bXdG/TyNL4v4vd3kybtMGVLAx+mX4D0iXU=
      - key: ACCOUNT_ID
        value: 7715028
      - key: TOPSTEP_USERNAME
        value: dcminsf
      - key: CONTRACT_ID
        value: CON.F.US.ENQ.M25
  - type: worker
    name: signalr-bridge
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start:bridge"
    envVars:
      - key: TOPSTEP_TOKEN
        fromEnvVar: TOPSTEP_TOKEN
      - key: CONTRACT_ID
        value: CON.F.US.ENQ.M25
      - key: PYTHON_BACKEND_URL
        fromEnvVar: https://topstep-bot.onrender.com/bridge_trade_event
