services:
  - type: web
    name: topstep-bot
    env: python
    plan: free
    buildCommand: pip install black && black . && pip install -r requirements.txt && pip install --upgrade pip && pip install python-multipart
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TOPSTEP_API_KEY
        value: 4s/YUAhW2bXdG/TyNL4v4vd3kybtMGVLAx+mX4D0iXU=
      - key: ACCOUNT_ID
        value: 7715028
      - key: TOPSTEP_USERNAME
        value: dcminsf
      - key: CONTRACT_ID
        value: CON.F.US.ENQ.M25
  - type: worker
    name: signalr-bridge
    env: node
    buildCommand: |
      cd bridge && npm install
    startCommand: |
      cd bridge && npm start
    envVars:
      - key: TOPSTEP_TOKEN 
        value: "your-initial-placeholder-or-old-token"
      - key: CONTRACT_ID
        value: CON.F.US.EP.M25
      - key: PYTHON_BACKEND_URL
        value: https://topstep-bot.onrender.com/bridge_trade_event
      - key: ACCOUNT_ID
        value: "7715028" 
      - key: N8N_USER_FILL_WEBHOOK_URL
        value: "https://dcminsf.app.n8n.cloud/webhook/user-fill-event-bridge"
      - key: BRIDGE_API_SECRET
        value: "rudy_tippi_caprice_carole_dcm" 
