services:
  # --- Service 1: Python FastAPI Application ---
  - type: web  # This hyphen is at the base level under services
    name: topstep-bot 
    env: python
    region: oregon # Or your preferred region
    plan: free # Or your current plan
    buildCommand: pip install black && black . && pip install -r requirements.txt # Python specific build
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT # Use $PORT for Render
    healthCheckPath: / # Or a specific health check endpoint in main.py
    envVars:
      - key: TOPSTEP_API_KEY
        value: 4s/YUAhW2bXdG/TyNL4v4vd3kybtMGVLAx+mX4D0iXU=
      - key: ACCOUNT_ID
        value: 7715028
      - key: TOPSTEP_USERNAME
        value: dcminsf
      - key: CONTRACT_ID
        value: CON.F.US.ENQ.M25
      - key: BRIDGE_API_SECRET 
        fromSecretKeyRef:
          name: topstep-secrets
          key: MY_BRIDGE_API_SECRET_KEY # Secret for Python to call bridge (if needed)
      - key: BRIDGE_INTERNAL_URL # If Python needs to call bridge internally
        value: http://signalr-bridge-svc:3001 # Example, using service discovery name
        
 - type: web  # This hyphen MUST be at the SAME indentation level as the one above
    name: signalr-bridge-svc 
    env: node
    region: oregon 
    plan: free 
    rootDir: bridge 
    buildCommand: npm install
    startCommand: node signalrBridge.js
    healthCheckPath: /health
    envVars:
      - key: TOPSTEP_TOKEN # This will be dynamically updated by n8n
        value: "initial_placeholder_or_expired_token" 
      - key: ACCOUNT_ID
        value: 7715028
      - key: N8N_USER_FILL_WEBHOOK_URL # Bridge needs to POST to n8n
        value: "https://dcminsf.app.n8n.cloud/webhook/user-fill-event-bridge" # Your actual n8n webhook
      - key: BRIDGE_API_SECRET # For securing the bridge's /update-token endpoint
        fromSecretKeyRef:
          name: topstep-secrets
          key: MY_BRIDGE_API_SECRET_KEY # This secret is used by n8n to call the bridge
      # RENDER WILL AUTOMATICALLY PROVIDE 'PORT' environment variable. 
      # Your signalrBridge.js uses process.env.PORT || 3001.
