services:
  - type: web
    name: topstep-python-bot # Renamed for clarity
    env: python
    plan: free # Or your chosen plan
    buildCommand: pip install black && black . && pip install -r requirements.txt && pip install --upgrade pip && pip install python-multipart
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT 
    envVars:
      - key: TOPSTEP_API_KEY
        value: 4s/YUAhW2bXdG/TyNL4v4vd3kybtMGVLAx+mX4D0iXU=
      - key: ACCOUNT_ID
        value: 7715028
      - key: TOPSTEP_USERNAME
        value: dcminsf
      - key: CONTRACT_ID
        value: CON.F.US.ENQ.M25
      - key: BRIDGE_API_SECRET # Python needs this to call the bridge if it ever needed to
        fromSecretKeyRef:
          name: topstep-secrets
          key: BRIDGE_API_SECRET

  - type: web # <<<< CHANGE THIS FROM 'worker'
    name: signalr-bridge-service # Give it a unique name
    env: node
    plan: free # Or your chosen plan
    buildCommand: |
      npm install
    startCommand: |
      node signalrBridge.js
    envVars:
      - key: TOPSTEP_TOKEN 
        value: "initial_placeholder_token" # Will be updated by n8n
      - key: ACCOUNT_ID
        value: 7715028
      - key: N8N_USER_FILL_WEBHOOK_URL # Bridge needs to know where to send fills
        value: "https://dcminsf.app.n8n.cloud/webhook/user-fill-event-bridge"
      - key: BRIDGE_API_SECRET # For securing its /update-token endpoint
        fromSecretKeyRef:
          name: topstep-secrets
          key: BRIDGE_API_SECRET
      # RENDER WILL PROVIDE THE PORT via process.env.PORT
      # Your signalrBridge.js already uses process.env.PORT
