services:
  - type: web
    name: topstep-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: hUcaJ5J88F92wlp2J0byZPRicRQwrW5EtPTNSkfZSac=
        sync: false
      - key: 305
        sync: false

